In [1]:
import numpy as np

Question -2

In [2]:
def strider(x,k):
  result=[]
  
  for i in range(0,len(x)-k+1):
    y=x[i:i+k]
    result.append(np.sum(y)/k)
  return result

In [3]:
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
result=strider(x,3)
print(result)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]


In [4]:
x=np.array([1,2,3,4,5]) 
N=5 
matrix = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


Question-1

In [24]:
inputArray=[1,2,3,4,5]
ipvector=np.array(inputArray)
n=5

def vanderMonde(input,n,increasing):
  if increasing:
    x=np.array([x**i for x in inputArray for i in range(n)]).reshape(len(inputArray),n)

  else:
    
    x=np.array([x**(N-1-i) for x in inputArray for i in range(n)]).reshape(len(inputArray),n)

  return x







In [25]:
inputArray=[1,2,3,4,5]
ipvector=np.array(inputArray)



In [26]:
vanderMonde(ipvector,6,True)


array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    5,   25,  125,  625, 3125]])

In [27]:
vanderMonde(ipvector,5,False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])